language: node_js

cache:
  directories:
    - "node_modules"

nodejs:
  - "lts/*"

before_install:
  - yarn install
  - yarn generate:queries
  - yarn generate:types

install:
  - yarn build

script:
  - yarn test

after_success:
  - yarn bundle

deploy:
  provider: releases
  api_key: "48da4cba612dad9c412f835f4c8219c68d4e3ba9"
  file: "wp-theme-scarecrow.zip"
  skip_cleanup: true
  on:
    tags: true
