version: '3.3'

services:
  database:
    image: mysql:latest
    restart: always
    volumes:
      - u:/data/blog-strootje:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: reallyhardpassword
      MYSQL_DATABASE: wp-blog-strootje
      MYSQL_USER: wp-strootje
      MYSQL_PASSWORD: test123123

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"

  server:
    build:
      context: ./
      dockerfile: ./.docker/wp-php.dockerfile
    image: wp-php
    restart: always
    depends_on:
      - database
    volumes:
      - u:/projects/blog-strootje:/var/www/html
    ports:
      - "80:80"
