#import "./Fragments/PostFields.gql"

query WP_FetchPosts( $first: Int, $before: String, $last: Int, $after: String ) {
	posts( first: $first, before: $before, last: $last, after: $after, where: { orderby: { field: DATE, order: DESC }}) {
		pageInfo {
			hasNextPage
			hasPreviousPage
		}

		edges {
			cursor
			node {
				...WP_PostFields
			}
		}
	}
}
