query WP_FetchSettings {
	allSettings {
		generalSettingsTitle
		generalSettingsDescription
		generalSettingsUrl

		readingSettingsIsStaticHomepage
		readingSettingsPageOnFront
		readingSettingsPageForPosts

		permalinkSettingsPermalinkStructure
		permalinkSettingsCategoryBase
		permalinkSettingsTagBase

		scarecrowSettingsImageProvider
		scarecrowSettingsFooterAbout
	}
}
