#import "./Fragments/CommentFields.gql"

query WP_FetchCommentsByPostId( $postId: Int! ) {
	postBy( postId: $postId ) {
		id
		comments( first: 9 ) {
			edges {
				cursor
				node {
					...WP_CommentFields
				}
			}
		}
	}
}
