#import "./Fragments/CategoryFields.gql"

query WP_FetchPosts {
	posts( first: 9 ) {
		nodes {
			id
			postId
			title
			uri
			content

			thumbnail

			categories {
				nodes {
					...WP_CategoryFields
				}
			}
		}
	}
}
