#import "./CategoryFields.gql"
#import "./UserFields.gql"

fragment WP_PostFields on Post {
	id
	postId
	title
	date
	link
	content

	thumbnail

	author {
		...WP_UserFields
	}

	categories {
		nodes {
			...WP_CategoryFields
		}
	}
}
